# Kernel makefile for motions sensors
#
# 
# SHMDS_ID_0103_01 mod S
# ifeq ($(CONFIG_MPU_SENSORS_MPU6515), y)
# obj-$(CONFIG_MPU_SENSORS_MPU6515)	+= mpu6515/
# else
obj-$(CONFIG_SHMDS)	+= motionsensor/
# endif
# SHMDS_ID_0103_01 mod E
