ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
#obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
obj-$(CONFIG_DW9804_ACT) += dw9804_actuator.o
